import './globals.css'
import { Inter } from 'next/font/google'
import { ReactQueryProvider } from '../providers/ReactQueryProvider'
import { ThemeProvider } from '@/providers/NextThemesProvider'
import { DarkModeMenu } from '@/components/darkModeMenu/DarkModeMenu'
import { NextUIThemeProvider } from '@/providers/NextUIThemeProvider'
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button} from "@nextui-org/react";
import { NavbarOriginal } from '@/components/navbar/NavbarOriginal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next Apps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
        <html lang="en">
          <body className={inter.className}>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <NextUIThemeProvider>
              <NavbarOriginal />
              <DarkModeMenu/>
              {children}
              <footer>FOOTER</footer>
              </NextUIThemeProvider>
            </ThemeProvider>
          </body>
        </html>
    </ReactQueryProvider>
  )
}
